platform :osx, '10.11'

workspace 'Kemo'
#project 'KemoApp.xcodeproj'

target 'KemoApp' do
  use_frameworks!

  # Pods for KemoApp  
 	pod 'CryptoSwift', '0.4.1'
	pod 'XCGLogger', '3.3'
	pod 'Starscream', '~> 1.1'

  target 'KemoAppTests' do
    pod 'CryptoSwift', '0.4.1'
		pod 'XCGLogger', '3.3'
		pod 'Starscream', '~> 1.1'
  end

end
