platform :osx, '10.11'

workspace 'Kemo'
#project 'KemoCore.xcodeproj'

target 'KemoCore' do
	use_frameworks!

	# Pods for KemoCore
	pod 'CryptoSwift', '0.5.1'
	pod 'XCGLogger', '3.3'
	pod 'Starscream', '~> 1.1'

	target 'KemoCoreTests' do
		pod 'CryptoSwift', '0.5.1'
		pod 'XCGLogger', '3.3'
		pod 'Starscream', '~> 1.1'
	end

end
